- .github/workflows/docker-main.yaml
- .github/workflows/release.yaml
- Dockerfile
- Dockerfile.release
- Makefile
- goreleaser.yaml
- Add release Docker image
- Add build steps to `Makefile`
- Add main branch Docker image 
n/a
> deployment: docker image and build commands

- api/tunnel.go
- go.sum
properly report a remote party as a peer address in `ConnectionStatusUpdate`.
https://github.com/pomerium/internal/issues/695
> fix peer address in listener connection updates

- .github/workflows/docker-main.yaml
- Dockerfile
- Dockerfile.release
- goreleaser.yaml
Ensure multi-arch release is consistent with other projects and add in a multiarch rolling `main` image.
https://github.com/pomerium/pomerium/pull/2925
https://github.com/pomerium/ingress-controller/pull/120
> deployment: multi-arch main image

- Dockerfile
- Makefile
We're starting to timeout when doing a cold lint run inside our docker image.
- add a timeout
- avoid linting during image build since it can take a while
n/a
> ci: fix lint during image build

- api/config.go
- api/config_test.go
The tag list wasn't properly adjusted after connection update. 
Fixes https://github.com/pomerium/desktop-client/issues/71
> fix empty tags

- .github/workflows/release.yaml
- goreleaser.yaml
Ensure we're using docker buildx for releases so that `TARGETARCH` is filled in properly.
#27
> deployment: fix multiarch release

- api/tunnel.go
In the API, client cert should be applied before CA
> client cert should be applied before CA

- .github/workflows/backport.yaml
- .github/workflows/docker-main.yaml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
Adopt https://github.com/ossf/scorecard standards for default github token permissions.
https://github.com/pomerium/internal/issues/813
> ci: set explicit token permissions

- .github/workflows/test.yaml
- api/config_server.go
- api/config_server_test.go
Import only stored in memory and didn't flush config to disk, that resulted in loss of records if you 
quit immediatelly after import. 
Fixes https://github.com/pomerium/internal/issues/868
> fix save after import

- tcptunnel/tcptunnel.go
On a 503 error, keep the cached JWT instead of deleting it.
Fixes https://github.com/pomerium/cli/issues/17
> tcptunnel: on 503, keep cached JWT

- .github/dependabot.yaml
- Dockerfile
- Dockerfile.release
Add docker support for dependabot. Also pin the docker dependencies.
> dependabot: add docker support

- .github/workflows/backport.yaml
- .github/workflows/docker-main.yaml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
- go.mod
Upgrade to go 1.18.
- https://github.com/pomerium/internal/issues/932
> go: upgrade to go 1.18

- api/listener_server.go
- api/server.go
- api/tunnel.go
- authclient/authclient.go
- authclient/authclient_test.go
- authclient/config.go
- cmd/pomerium-cli/api.go
- cmd/pomerium-cli/kubernetes.go
- cmd/pomerium-cli/main.go
- cmd/pomerium-cli/proxy.go
- cmd/pomerium-cli/tcp.go
- tcptunnel/config.go
- tcptunnel/tcptunnel.go
You can now pass service accounts to CLI commands instead of going through the browser auth flow. The CLI flags are:
- `service-account`: the JWT as a string
- `service-account-file`: the path to a file containing the JWT. Spaces are trimmed.
Fixes #160
> authclient: add support for service accounts

- api/tunnel.go
- cmd/pomerium-cli/tcp.go
- tcptunnel/urls.go
- tcptunnel/urls_test.go
Add extended TCP support so that in addition to:
```
pomerium-cli tcp redis.example.com:6379
```
You can also use:
```
pomerium-cli tcp tcp+https://proxy.example.com/redis.example.com:6379
```
The existing `pomerium-url` option also still works.
Fixes https://github.com/pomerium/internal/issues/1201
> tcp: add extended tcp support

- api/config_server.go
- api/config_server_test.go
Fixes connection deletion that did not persist the change. 
Fixes https://github.com/pomerium/desktop-client/issues/175
> fix delete

- go.mod
- go.sum
> set core to v0.21.0

- .github/workflows/release.yaml
- .github/workflows/test.yaml
- .tool-versions
- Dockerfile
- go.mod
Fixes https://github.com/pomerium/internal/issues/1339
> upgrade go

- .github/workflows/release.yaml
Update the 'Release' GitHub Action workflow to replace the deprecated `::set-output` command with the newer `$GITHUB_OUTPUT` file mechanism.
- https://github.com/pomerium/internal/issues/1511
> replace ::set-output in release action

- .github/workflows/release.yaml
Simplify git checkout into one step rather than two. Pin GoReleaser to v1.18.2 to avoid the removal of the `nfpms.replacements` setting for now.
This is in preparation for splitting out the macOS and Windows builds to separate jobs within the workflow.
> release: minor clean up

- .github/workflows/release.yaml
- goreleaser.yaml
Update the GitHub Actions 'Release' workflow to build for macOS and Windows within separate jobs, so we can perform the macOS builds on a macOS runner and the Windows builds on a Windows runner. This is in preparation for building against OS-specific libraries (with cgo).
Add a separate job at the beginning for setting version flags to be shared across all three build jobs, and a separate job at the end for combining all of the release asset checksums into one file.
In preparation for #308.
> release: build for macOS and Windows separately

- go.mod
- third_party/ecpsigner/LICENSE
- third_party/ecpsigner/darwin/keychain/keychain.go
- third_party/ecpsigner/darwin/keychain/keychain_test.go
- third_party/ecpsigner/windows/ncrypt/cert_util.go
- third_party/ecpsigner/windows/ncrypt/cert_util_test.go
- third_party/ecpsigner/windows/ncrypt/ncrypt.go
Vendor some files from the internal/signer directory in https://github.com/googleapis/enterprise-certificate-proxy/ into a new package 'third_party/ecpsigner'.
The enterprise-certificate-proxy code is licensed under the Apache License 2.0. These files were copied as of the v0.2.5 tag in that repository. No modifications were made to these files.
In preparation for https://github.com/pomerium/cli/issues/308.
> vendor internal/signer from enterprise-certificate-proxy

- Makefile
- certstore/certstore.go
- certstore/certstore_darwin.go
- certstore/certstore_stub.go
- certstore/certstore_windows.go
- certstore/credential.go
- cmd/pomerium-cli/main.go
- version/version.go
- version/version_test.go
Add a new package `certstore` to provide a common interface for the macOS and Windows platform-specific trust store methods from the vendored `third_party/ecpsigner` code.
Add a new `--client-cert-issuer-cn` flag to the tcp command using this functionality. Register this flag only when the feature is supported.
Update the version output to add a new 'Features:' line to indicate whether pomerium-cli was compiled with support for this feature. Give the macOS integration the feature name 'keychain' and the Windows integration the feature name 'ncrypt'.
- https://github.com/pomerium/cli/issues/308
> integrate with system cert store

- cmd/pomerium-cli/version.go
Currently pomerium-cli has both a `version` command and a `--version` flag, and the output differs slightly between these two. To ensure that these two stay in sync, change the `version` command so that it delegates to the root command with the args overwritten to contain just `--version`.
Fixes #336.
> update version command

- third_party/ecpsigner/windows/ncrypt/cert_util.go
On Windows, trying to open the LocalMachine cert store may require administrator permissions for the default mode (read/write). However, if we include the `CERT_STORE_READONLY_FLAG` option this appears to allow opening the cert store without running as admin.
Add a Pomerium copyright line to the modified file, to serve as "prominent notice" that this file has been modified, per clause 4(b) of the Apache License 2.0 (on the recommendation of https://opensource.stackexchange.com/a/13150).
> ncrypt: open cert store in readonly mode

- api/config.go
- api/config_test.go
The `pomerium-cli api` command will persist its state as a protobuf serialized to JSON. If a newer version of pomerium-cli introduces new fields in this protobuf message, an older version of pomerium-cli may not be able to start — currently it will exit if there is any error when unmarshaling this state.
(Ordinarily, adding a field to a proto message is a backwards-compatible change: any software built with the older definition of the proto will generally not notice the new field. However, it looks like the protojson library `Unmarshal()` method will return an error for any unknown fields present in the JSON data.)
Let's change this behavior, by setting the `DiscardUnknown` option. This way, an older pomerium-cli binary won't quit on startup if it encounters an unknown option. Instead it …
> api: discard unknown config proto fields

- Dockerfile
Update the `golang:1.21.3-bookworm` base image to the current multi-platform manifest digest for this tag.
- https://github.com/pomerium/internal/issues/1519#issuecomment-1828428428
> update Go base docker image

- api/tunnel.go
- certstore/certstore.go
- certstore/certstore_darwin.go
- certstore/certstore_stub.go
- certstore/certstore_test.go
- certstore/certstore_windows.go
- cmd/pomerium-cli/main.go
- third_party/ecpsigner/darwin/keychain/keychain.go
- third_party/ecpsigner/windows/ncrypt/cert_util.go
Replace the `--client-cert-issuer-cn` option with a new set of options:
-  `--client-cert-from-store`  enables searching the OS cert store overall
-  `--client-cert-issuer`      selects between multiple available certificates based on an attribute of the cert's Issuer name (e.g. `"CN=Trusted CA Name"`)
-  `--client-cert-subject`     selects between multiple available certificates based on an attribute of the cert's Subject name (e.g. `"OU=Organization Unit Name"`
If only the first option is set, the cert store will be searched based on any CA names provided in the TLS Certificate Request message. This will be sufficient for devices with only a single matching certificate. (Note that this does requires Pomerium v0.23 or later, as v0.22 and earlier do not advertise trusted CA names in the …
> expand client cert search capabilities

- cmd/pomerium-cli/cache.go
- internal/cache/cache.go
- jwt/jwtcache.go
Add commands:
```bash
pomerium-cli cache clear
pomerium-cli cache location
```
Fixes https://github.com/pomerium/cli/issues/279
> cli/cmd: add commands for viewing the cache location and clearing it

- certstore/certstore.go
- certstore/certstore_test.go
Change the semantics of the `--client-cert-issuer` and `--client-cert-subject` options to support name attributes with multiple values. Allow a filter condition to match on any value for a particular attribute, rather than requiring a matching attribute to have just one single value.
- https://github.com/pomerium/cli/issues/448
> certstore: support multi-valued name attributes

- .github/workflows/lint.yml
- .tool-versions
For https://github.com/pomerium/internal/issues/1835
Update golangci-lint to v1.60.1
> cli/ci: update lint

- api/server.go
- api/tunnel.go
- cmd/pomerium-cli/proxy.go
- cmd/pomerium-cli/tcp.go
- tunnel/config.go
- tunnel/events.go
- tunnel/tunnel.go
- tunnel/tunnel_test.go
- tunnel/urls.go
- tunnel/urls_test.go
In preparation for future changes, rename `tcptunnel` to `tunnel`.
- #466
> tcptunnel: rename to tunnel

- .github/workflows/release.yaml
- msi/PomeriumCli.wxs
- msi/WixUI_InstallDir_NoLicense.wxs
This PR refactors the release workflow to use a matrix strategy and adds a step to build MSI packages for Windows.
- Instead of using a shell loop to build for ARM and x86 it uses the GitHub actions matrix feature to build both in parallel.
This makes the builds faster and easier to troubleshoot
- It separates the build and archive steps into two distinct steps to make it more clear and ease troubleshooting
- It adds a step that uses the Wix toolkit to build an MSI package for Windows. The MSI is very simple and will simply install the exe file in with the option for the user to change this `%ProgramFiles%\Pomerium\Pomerium CLI\`
None
> Refactor release workflow and add MSI build

- authclient/authclient.go
- cmd/pomerium-cli/cache.go
- cmd/pomerium-cli/kubernetes.go
Currently we rely on the expiration timestamp in the cached credentials to know when they need to be refreshed. This PR updates the code to not set the expiration timestamp at all if its not set in the JWT, and to always verify the JWT by attempting to access `/api` with the token. If access fails we assume the credentials are invalid.
- https://github.com/pomerium/internal/issues/1983
> kubernetes: verify cached bearer tokens

- tunnel/tunnel.go
- tunnel/tunnel_http1.go
- tunnel/tunnel_http2.go
- tunnel/tunnel_http3.go
Currently if a tunnel receives a `403` we will attempt to login again the next time the tunnel is created. This PR updates the code to not clear the JWT credentials on `403`s, since those credentials won't change if the user logs in again.
- https://linear.app/pomerium/issue/ENG-1834/udp-infinite-authentication-loop-instead-of-access-denied
> tunnel: handle forbidden responses

- cmd/pomerium-cli/main.go
- internal/httputil/transport.go
- tunnel/tunnel_http1.go
- tunnel/tunnel_tcp.go
Several changes:
- log the probe requests for debugging.
- disable redirects for the probe request, so we don't inadvertently get back the authenticate service's HTTP response
- disable http/2 and only support http/3 or http/1 (for https://github.com/pomerium/pomerium/issues/5431)
- force http/1 by adding it to the ALPN protocols for TLS connections
- [ENG-2131](https://linear.app/pomerium/issue/ENG-2131/cli-tcp-tunneling-only-works-with-http3)
- [ENG-2122](https://linear.app/pomerium/issue/ENG-2122/cli-tunnel-picker-should-not-follow-redirects)
> log probe request, disable redirects, disable http/2

- .github/workflows/release.yaml
- goreleaser.yaml
The macOS and Windows binaries are currently built separately from GoReleaser (in order to be able to build against OS-native libraries using cgo). As a result, GoReleaser builds only the Linux binaries, and so it will update the Homebrew tap to be Linux-only.
Remove the `brews` section from the GoReleaser configuration, and instead trigger the replacement [`repository_dispatch` workflow](https://github.com/pomerium/homebrew-tap/blob/master/.github/workflows/cli.yaml) in the pomerium/homebrew-tap repo.
https://linear.app/pomerium/issue/ENG-1028/fix-homebrew-tap-automation
> ci: rework homebrew-tap updates

- .github/workflows/release.yaml
Signing and notarizing binaries for distribution outside of the apple app stores involves using developer ID private key material that's precious.  To avoid accidents and potentially signing rogue software or worse, this moves the build to a private repo.
> Move mac builds to internal repo so they can be properly signed and notarized

- .github/workflows/release.yaml
goreleaser changes prerelease version string for debs and rpms to mean the correct thing.
a tilde (~) in an rpm/deb package indicates to the package manager that it should be ranked lower than the unadorned version.
e.g. 0.29.2~rc1 < 0.29.2
> Fix prerelease version

- cmd/pomerium-cli/cache.go
Update the permissions for cached k8s ExecCredentials to match the permissions for cached JWTs.
https://linear.app/pomerium/issue/ENG-2205/
> standardize cached credential file permissions
